services:
  mysql:
    image: mysql:8.4
    container_name: core-api-mysql
    environment:
      MYSQL_DATABASE: core_api
      MYSQL_USER: core_api
      MYSQL_PASSWORD: core_api
      MYSQL_ROOT_PASSWORD: root-local-change-me
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./sql/schema_and_seed.sql:/docker-entrypoint-initdb.d/001-schema.sql:ro
    restart: unless-stopped

  core-api:
    build: .
    container_name: core-api
    user: "0:0"
    depends_on:
      - mysql
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      #- /home/maksim/.ssh_proxy:/home/appuser/.ssh:ro
      - /home/maksim/.ssh:/home/appuser/.ssh:ro
      - ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}
      - ./config:/etc/pctl/config:ro
      - ./policies:/etc/pctl/policies:ro
      - ./api-logs:/var/log/core-api
    environment:
      PYTHONPATH: /app
      SSH_AUTH_SOCK: ${SSH_AUTH_SOCK}
      PCTL_API_TOKEN: dev-local-token-change-me
      PCTL_SUPERADMIN_EMAIL: superadmin@local
      PCTL_SUPERADMIN_USERNAME: superadmin
      PCTL_SUPERADMIN_PASSWORD: superadmin-change-me
      PCTL_AUTH_ACCESS_TTL_MINUTES: 480
      PCTL_IMPORT_SSH_CONFIG_MODE: ${PCTL_IMPORT_SSH_CONFIG_MODE:-off}
      PCTL_IMPORT_SSH_CONFIG_MARKER: ${PCTL_IMPORT_SSH_CONFIG_MARKER}
      PCTL_SSH_CONFIG: /home/appuser/.ssh/config
      PCTL_SSH_KNOWN_HOSTS: /home/appuser/.ssh/known_hosts
      PCTL_CONFIG: /etc/pctl/config/config.yml
      PCTL_DATABASE_URL: mysql+pymysql://core_api:core_api@mysql:3306/core_api
      PCTL_LOG_DIR: /var/log/core-api/jobs
      PCTL_AUDIT_LOG: /var/log/core-api/audit/audit.jsonl
    restart: unless-stopped


  web:
    build: ../ai-proxy-web
    container_name: ai-proxy-web
    depends_on:
      - core-api
    ports:
      - "127.0.0.1:8081:80"
    restart: unless-stopped

  pctl-tests:
    build: .
    container_name: pctl-tests
    volumes:
      - ./config:/etc/pctl/config:ro
      - ./policies:/etc/pctl/policies:ro
    environment:
      PYTHONPATH: /app
      PCTL_CONFIG: /etc/pctl/config/config.yml
      PCTL_TEST_SERVER: lifeorient
    command: ["pytest", "-q"]
    profiles:
      - test

  adminer:
    image: adminer:5.0.6-standalone
    container_name: adminer
    restart: unless-stopped
    ports:
      - 8088:8080
    links:
      - mysql
    environment:
      ADMINER_DEFAULT_DRIVER: 'MySQL'
      ADMINER_DEFAULT_SERVER: 'mysql'
      ADMINER_DEFAULT_DB: 'core_api'
      ADMINER_DEFAULT_USER: 'core_api'
      ADMINER_DEFAULT_PASSWORD: 'core_api'
      ADMINER_DESIGN: 'flat'

