CREATE TABLE IF NOT EXISTS teams (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) NOT NULL UNIQUE,
  slug VARCHAR(64) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS projects (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  slug VARCHAR(64) NOT NULL,
  team_id INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_projects_team_slug (team_id, slug),
  CONSTRAINT fk_projects_team FOREIGN KEY (team_id) REFERENCES teams(id)
);

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(128) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  role VARCHAR(32) NOT NULL,
  team_id INT NULL,
  password_hash VARCHAR(512) NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_login TIMESTAMP NULL DEFAULT NULL,
  public_key TEXT NULL,
  CONSTRAINT fk_users_team FOREIGN KEY (team_id) REFERENCES teams(id)
);

CREATE TABLE IF NOT EXISTS proxies (
  id INT AUTO_INCREMENT PRIMARY KEY,
  proxy VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS servers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) NOT NULL UNIQUE,
  host VARCHAR(255) NOT NULL,
  ip VARCHAR(64) NULL,
  proxy_id INT NULL,
  team_id INT NULL,
  project_id INT NULL,
  port INT NOT NULL DEFAULT 22,
  environment VARCHAR(64) NOT NULL DEFAULT 'dev',
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_servers_proxy FOREIGN KEY (proxy_id) REFERENCES proxies(id),
  CONSTRAINT fk_servers_team FOREIGN KEY (team_id) REFERENCES teams(id),
  CONSTRAINT fk_servers_project FOREIGN KEY (project_id) REFERENCES projects(id)
);

CREATE TABLE IF NOT EXISTS user_sessions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  session_uid VARCHAR(64) NOT NULL UNIQUE,
  user_id INT NOT NULL,
  token_hash VARCHAR(255) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP NOT NULL,
  last_used_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  revoked_at TIMESTAMP NULL DEFAULT NULL,
  revoked_reason VARCHAR(128) NULL,
  rotated_from_session_id INT NULL,
  user_agent VARCHAR(255) NULL,
  ip_address VARCHAR(64) NULL,
  CONSTRAINT fk_user_sessions_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS jobs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  request_id VARCHAR(64) NOT NULL UNIQUE,
  user_id INT NULL,
  auth_session_id INT NULL,
  server_id INT NULL,
  server_name VARCHAR(128) NOT NULL,
  client_type VARCHAR(16) NOT NULL,
  command TEXT NOT NULL,
  status VARCHAR(16) NOT NULL,
  stdout_lines INT NOT NULL DEFAULT 0,
  stderr_lines INT NOT NULL DEFAULT 0,
  started_at TIMESTAMP NULL DEFAULT NULL,
  finished_at TIMESTAMP NULL DEFAULT NULL,
  exit_code INT NULL,
  hidden_at TIMESTAMP NULL DEFAULT NULL,
  hidden_by_user_id INT NULL,
  CONSTRAINT fk_jobs_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_jobs_server FOREIGN KEY (server_id) REFERENCES servers(id)
);

CREATE TABLE IF NOT EXISTS actions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(64) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS audit_events (
  id INT AUTO_INCREMENT PRIMARY KEY,
  request_id VARCHAR(64) NULL,
  user_id INT NULL,
  server_id INT NULL,
  action_id INT NULL,
  session_id INT NULL,
  resource VARCHAR(255) NOT NULL,
  result VARCHAR(64) NOT NULL,
  ip_address VARCHAR(64) NULL,
  details_json TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_audit_server FOREIGN KEY (server_id) REFERENCES servers(id),
  CONSTRAINT fk_audit_action FOREIGN KEY (action_id) REFERENCES actions(id)
);

CREATE TABLE IF NOT EXISTS job_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  job_id INT NOT NULL,
  log_file VARCHAR(1024) NOT NULL,
  size_bytes INT NOT NULL DEFAULT 0,
  line_count INT NOT NULL DEFAULT 0,
  CONSTRAINT fk_job_logs_job FOREIGN KEY (job_id) REFERENCES jobs(id)
);

CREATE TABLE IF NOT EXISTS command_streams (
  id INT AUTO_INCREMENT PRIMARY KEY,
  job_id INT NOT NULL,
  share_token VARCHAR(128) NOT NULL UNIQUE,
  is_public BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP NULL DEFAULT NULL,
  CONSTRAINT fk_command_streams_job FOREIGN KEY (job_id) REFERENCES jobs(id)
);

CREATE TABLE IF NOT EXISTS tokens (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) NOT NULL UNIQUE,
  token_hash VARCHAR(255) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT IGNORE INTO actions (name) VALUES
  ('EXEC_ALLOWED'),
  ('EXEC_DENIED'),
  ('LOGIN_SUCCESS'),
  ('LOGIN_FAILURE'),
  ('LOGOUT'),
  ('SESSION_REVOKED'),
  ('SUSPICIOUS_AUTH'),
  ('CANCEL'),
  ('PASSWORD_CHANGED'),
  ('SESSION_ROTATED'),
  ('SESSION_HIDDEN');

INSERT IGNORE INTO teams (name, slug) VALUES
  ('Platform', 'platform');

INSERT IGNORE INTO proxies (proxy) VALUES
  ('direct');
